#
# (c) 2023 Thales Group. All rights reserved.
# Author: Anurag Jain, Developer Advocate, Thales
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
  - name: "Sample playbook for interacting with Interfaces on CipherTrust Manager"
    hosts: localhost
    connection: local

    vars_files:
      - vars/interfaceMgmt.yml

    tasks:
    - name: "Create Interface"
      thalesgroup.ciphertrust.interface_save:
        localNode: "{{ this_node_connection_string }}"
        op_type: create
        port: 9006
        auto_registration: false
        interface_type: nae
        mode: no-tls-pw-opt
        network_interface: all
      register: interface
      ignore_errors: true

    - name: Paused for verifying trial license activation, press enter to continue
      ansible.builtin.pause:

    - name: "Patch Interface"
      thalesgroup.ciphertrust.interface_save:
        localNode: "{{ this_node_connection_string }}"
        op_type: patch
        interface_id: nae_all_9006
        port: 9007

    - name: "Add Cert to Interface"
      thalesgroup.ciphertrust.interface_actions:
        localNode: "{{ this_node_connection_string }}"
        op_type: put_certificate
        interface_id: "interface_identifier"
        certificate: "cert_key_data"
        format: PEM

    - name: "Enable Interface"
      thalesgroup.ciphertrust.interface_actions:
        localNode: "{{ this_node_connection_string }}"
        op_type: enable
        interface_id: "interface_identifier"

    - name: "Disable Interface"
      thalesgroup.ciphertrust.interface_actions:
        localNode: "{{ this_node_connection_string }}"
        op_type: disable
        interface_id: "interface_identifier"

    - name: "Restore default TLS Ciphers"
      thalesgroup.ciphertrust.interface_actions:
        localNode: "{{ this_node_connection_string }}"
        op_type: restore-default-tls-ciphers
        interface_id: "interface_identifier"

    - name: "Create CSR"
      thalesgroup.ciphertrust.interface_actions:
        localNode: "{{ this_node_connection_string }}"
        op_type: csr
        interface_id: "interface_identifier"
        cn: "csr_cn"

    - name: "Auto Generate Server Certificate"
      thalesgroup.ciphertrust.interface_actions:
        localNode: "{{ this_node_connection_string }}"
        op_type: auto-gen-server-cert
        interface_id: "interface_identifier"

    - name: "Use certificate"
      thalesgroup.ciphertrust.interface_actions:
        localNode: "{{ this_node_connection_string }}"
        op_type: use-certificate
        interface_id: "interface_identifier"
        copy_from: "Name_Source_Interface"

    - name: Debug Output
      debug: var=output